### ISSUE TITLE
. Gamestream files with AKL

### ISSUE THREAD

**Issue by mousex110** [chrisism/repository.chrisism#2]
Great work with AEL and AKL. How would I go about opening .gamestream files using either AEL or AKL? I am using a modified moonlight apk which saves these files. Any help would be greatly appreciated. I appreciate what you are doing as Kodi has a great potential for games.

**Comment by chrisism** [comment]
Currently I apply a fixed set of arguments to launch the APK from Kodi. Based on the original Moonlight version. So in that case I would need to know how it should be called with the gamestream files.
But why do you need the separate gamestream files? With my latest gamestream plugin for AKL in Kodi you can simply import all the games from your gamestream server/pc and create your game collections how you want in AKL. You only need the nvidia app or moonlight to startup the game. Works as a charm with Kodi Nexus. Try it out if that is already sufficient (extra instructions about keys https://github.com/chrisism/script.akl.nvgamestream#readme), let me know.

Also, best place for updates, contact and info, follow: https://forum.kodi.tv/showthread.php?tid=366351

**Comment by mousex110** [comment]
Legend, will give it a ago. Sounds like a good solution. Saves getting root access and using modified apk. Thanks for the help

**Comment by chrisism** [comment]
No problem. Keep me informed if it all works out. Setting up the connection first time can be a little tricky. In the end you will need a valid pair of certificates to be used by AKL to communicate with the gamestream pc. 
I will close this issue, preferred to use the forum thread for other communication.
